export const methodEnByIndex = [
  'Acidification',
  'Climate change',
  'Climate change-Biogenic',
  'Climate change-Fossil',
  'Climate change-Land use and land use change',
  'Ecotoxicity, freshwater',
  'Ecotoxicity, freshwater-inorganics',
  'Ecotoxicity, freshwater-organics',
  'Resource use, fossils',
  'Eutrophication, freshwater',
  'Eutrophication marine',
  'Eutrophication, terrestrial',
  'Human toxicity, cancer',
  'Human toxicity, cancer-inorganics',
  'Human toxicity, cancer-organics',
  'Human toxicity, non-cancer',
  'Human toxicity, non-cancer_inorganics',
  'Human toxicity, non-cancer_organics',
  'Ionising radiation, human health',
  'Land use',
  'Resource use, minerals and metals',
  'Ozone depletion',
  'EF-particulate Matter',
  'Photochemical ozone formation - human health',
  'Water use',
];
